name: Publish

on:
  - pull_request
  # - push

jobs:
  publish_job:
    runs-on:
      - ubuntu-latest
    name: Publish charts
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.5.4
        with:
          dir_names: true
          dir_names_exclude_root: true
          dir_names_max_depth: 2
          path: charts
